server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: blog_user
    password: blog_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24小时 (毫秒)
  refresh-expiration: 604800000  # 7天 (毫秒)

logging:
  level:
    com.blog: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# PDF配置
pdf:
  font-path: src/main/resources/fonts/NotoSerifCJKsc-Regular.otf
  template-dir: src/main/resources/templates/pdf/
  output-dir: output/pdf/
  default-font-size: 12
  embed-font: true